spring:
  profiles: dev
  logging:
    config: classpath:logback.xml
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/vip-manager
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle : true
      validationQuery: select 1 from dual
mybatis:
  #实体类所做包
  type-aliases-package: com.vip.model.*
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*Mapper.xml
server:
  port: 8081
  context-path: /vip-manager